apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = AKIASBTFGKHMTS23MPMJ
    aws_secret_access_key = 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